### ISSUE TITLE
Order of exercises?

### ISSUE THREAD

**Issue by catb0t** [exercism/xfactor#4]
I've been reading the piles of documentation littered throughout the Exercism project, and I'm fairly clear on _how_ to implement problems. What I find very confusing or vague at best is, how to know which exercise I should put after this one?

Obviously, the `hello-world` exercise is easiest -- string concatenation / formatting, so it's first. Leap year (which is the second exercise in Python, JS, Racket and probably lots of others) is a little bit harder, but not very hard, so it goes at spot 2.

I haven't read all or even most of the problems in the `x-common` repo, but I kinda assume they get harder as the track progresses... yes? If this is the case, should I order problems in the same way as another track that has many problems implemented? Or does it not matter?

**Comment by kytrinyx** [comment]
> I've been reading the piles of documentation littered throughout the Exercism project

Ow, yeah I'm so sorry about that! I really need to figure out how to put the right documentation in the right place.

> I haven't read all or even most of the problems in the x-common repo, but I kinda assume they get harder as the track progresses... yes?

Yeah, that's the idea, but it's kind of a rough guess when we start a new track, because different languages have different concepts that get introduced in the various problems.

Take a look at how the Rust track is tackling this: https://github.com/exercism/xrust/issues/127

**Comment by catb0t** [comment]
Sweet, that's really helpful!
